---
#
# We create a per-tenant default Namespace, where
# the Tenant users (i.e. Owners) live.
# This is created by the parent GitOps reconciler.
#
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev-team
    capsule.clastix.io/tenant: dev-team
  name: dev-team

---
#
# A Tenant as a set of Namespaces, is owned by the
# gitops-reconciler Tenant Owner.
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-reconciler
  namespace: dev-team

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: max
  namespace: dev-team

---
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
metadata:
  name: dev-team
spec:
  additionalRoleBindings:
  - clusterRoleName: cluster-admin
    subjects:
    - name: gitops-reconciler
      kind: ServiceAccount
      namespace: dev-team
  owners:
  - name: system:serviceaccount:dev-team:gitops-reconciler
    kind: ServiceAccount
  - name: system:serviceaccount:dev-team:max
    kind: ServiceAccount

---
#
# The service account gitops-reconciler (in dev-team Namespace)
# has to be part of Capsule group, pass through Capsule access control.
#
apiVersion: capsule.clastix.io/v1alpha1
kind: CapsuleConfiguration
metadata:
  name: default
spec:
  userGroups:
  - system:serviceaccounts:dev-team

---
#
# We need the Tenant Owner and Tenant GitOps reconciler
# to be able to operate also on Custom Resources
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dev-team
  name: gitops-reconciler
  namespace: dev-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: gitops-reconciler
  namespace: dev-team

---
#
# Needed to provision namespaces with kubectl apply
# the GitOps way
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capsule-namespace-provisioner-gitops-dev-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capsule-namespace-provisioner-gitops
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:dev-team
